<?php
/**
 * @file
 *
 * validate login information from techcenterboise.com and log the user in as
 * a given user
 */

/**
 * Implementation of hook_menu().
 */
function tcbusermanagementclient_menu() {
  $items = array();
  $items['admin/settings/tcbusermanagementclient'] = array(
    'title' => 'TCB User Management',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tcbusermanagementclient_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * give the admin settings form
 */
function tcbusermanagementclient_admin_settings() {
  $form = array();
  $form['tcbusermanagementclient_uid'] = array(
    '#title' => t('Logged in user uid'),
    '#description' => t('When the user logs in what user on this site do you want them to be logged in as?'),
    '#default_value' => variable_get('tcbusermanagementclient_uid', ''),
    '#type' => 'textfield',
    '#autocomplete_path' => 'user/autocomplete',
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_form_alter().
 */
function tcbusermanagementclient_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login_block':
    case 'user_login':
      array_unshift($form['#validate'],'tcbusermanagementclient_login_validate') ;
      break;
      
  }
}

/**
 * confirm that the user is either a a user on this system, or an authorized
 * user on techcenterboise.com
 */
function tcbusermanagementclient_login_validate($form, &$form_state) {
  $form_values = $form_state['values'];
  if ((strpos($form_values['name'], '@techcenterboise.com') !== FALSE) && variable_get('tcbusermanagementclient_uid', '')) {
    $name = explode('@techcenterboise.com', $form_values['name']);
    $url = 'http://dev-authtechcenterboisecom.pantheon.io/tcbusermanagementserver/authenticate_user/'. urlencode($name[0]) .'/'. $form_values['pass'];
    $data = drupal_http_request($url, $headers = array(), $method = 'GET', $data = NULL, $retry = 3);
    $data = drupal_http_request($url);
    $result = $data->data;
    $tokens = array(
      '@username' => $name[0],
      
    );
    if ($result == 'true') {
      global $user;
      $account = user_load(array('name' => variable_get('tcbusermanagementclient_uid', '')));
      $tokens['@this_user'] = $account->name;
      $user = $account;
      watchdog('user_management', '@username has successfully logged in by TCB User Management as user @this_user', $tokens);
      user_authenticate_finalize($form_values);
    }
    else {
      watchdog('user_management', '@username has attempted to log in by TCB User Management', $tokens);
    }
  }
}

/**
 * Implementation of hook_wlw_blogapi_user_authenticate().
 */
function tcbusermanagementclient_wlw_blogapi_user_authenticate($username, $password) {
  global $user;
  if ((strpos($username, '@techcenterboise.com') !== FALSE) && variable_get('tcbusermanagementclient_uid', '')) {
    $name = explode('@techcenterboise.com', $username);
    $url = 'http://dev-authtechcenterboisecom.pantheon.io/tcbusermanagementserver/authenticate_user/'. urlencode($name[0]) .'/'. $password;

    $data = drupal_http_request($url);
    $result = $data->data;
    $tokens = array(
      '@username' => $name[0],
    );
    if ($result == 'true') {
      $user = user_load(array('name' => variable_get('tcbusermanagementclient_uid', '')));
      $tokens['@this_user'] = $account->name;
      watchdog('user_management', '@username has successfully logged in by TCB User Management as user @this_user', $tokens);
    }
    else {
      watchdog('user_management', '@username has attempted to log in by TCB User Management', $tokens);
    }
  }
}
